"""initial migration

Revision ID: 834e75ba9532
Revises: 
Create Date: 2022-09-06 20:45:48.208361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834e75ba9532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
