"""empty message

Revision ID: cab6c0d65ab0
Revises: 214e2ff89cf2
Create Date: 2022-10-28 00:05:24.198137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab6c0d65ab0'
down_revision = '214e2ff89cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_pic')
    # ### end Alembic commands ###
