"""added foreign key

Revision ID: d73dffef956c
Revises: 1d36e68eaf46
Create Date: 2022-09-12 12:21:50.722895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73dffef956c'
down_revision = '1d36e68eaf46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'users', ['poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'poster_id')
    # ### end Alembic commands ###
